# Generated by Django 3.1 on 2022-10-11 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79e1ff4c-77f1-458c-a8a8-557efeb679b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
