# Generated by Django 3.1 on 2022-10-11 05:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221011_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('addf280b-fca3-403d-855b-e7f78f7bcb87'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='category_image/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='shop.category')),
            ],
            options={
                'verbose_name': 'Categorys',
                'verbose_name_plural': 'Categorys',
            },
        ),
    ]
