# Generated by Django 3.1 on 2022-10-11 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221011_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e9056386-76de-4b50-951f-c3b0150fc08a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_price', models.FloatField(blank=True, max_length=255, null=True)),
                ('discount_persent', models.IntegerField(blank=True, help_text='Please put any value between 1 to 99', max_length=50, null=True)),
                ('discount_price', models.FloatField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='products_image/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
