# Generated by Django 3.1 on 2022-10-11 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221011_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7045edf8-f3c3-4ab8-b5ff-80cf79a0a9a1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_persent',
            field=models.IntegerField(blank=True, help_text='Please put any value between 1 to 99', null=True),
        ),
    ]
