# Generated by Django 3.1 on 2022-10-11 10:23

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221011_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e3234b6f-56b1-41f7-8036-111d2a0f7fe5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
