# Generated by Django 3.1 on 2022-10-11 10:51

from django.db import migrations, transaction



class Migration(migrations.Migration):
    # atomic= False

    dependencies = [
        ('shop', '0007_auto_20221011_1023'),
    ]

    operations= [
    ]
