# Generated by Django 3.1 on 2022-10-11 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221011_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4950f174-fcbb-48e9-8d65-7836f61c60f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
