# Generated by Django 3.1 on 2022-10-11 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221011_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('589483b3-c3e3-4c02-80a5-c4202bb514e8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
