# Generated by Django 3.1 on 2022-10-11 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20221011_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('83a393fe-4988-459d-839e-0fc807828f5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
