# Generated by Django 3.1 on 2022-10-11 11:02

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221011_1059'),
    ]

    operations = [

    ]
