# Generated by Django 3.1 on 2022-10-11 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20221011_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b0272f1e-e375-41da-b08b-8cf925c19358'), editable=False, primary_key=True, serialize=False),
        ),
    ]
