# Generated by Django 3.1 on 2022-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20221011_1106'),
    ]

    operations = [

    ]
