# Generated by Django 3.1 on 2022-10-11 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20221011_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e1d7c9b-4640-4125-a4a2-f3ed370c2a9b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
