# Generated by Django 3.1 on 2022-10-12 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20221012_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c538b687-cf3e-4ae5-bf38-8a6bfb58a502'), editable=False, primary_key=True, serialize=False),
        ),
    ]
