# Generated by Django 3.1 on 2022-11-03 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20221103_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7d067474-b6ed-48c4-872b-7665018a85a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
