# Generated by Django 3.1 on 2022-11-03 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20221103_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('85534869-8e33-451d-af31-e049ef705740'), editable=False, primary_key=True, serialize=False),
        ),
    ]
