# Generated by Django 3.1 on 2022-11-03 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20221103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1970b6c9-e1a7-4567-91a8-f675d0207a71'), editable=False, primary_key=True, serialize=False),
        ),
    ]
