# Generated by Django 3.1 on 2022-11-03 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20221103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9d04e45b-6f79-4f24-aeeb-47b6ecc79a67'), editable=False, primary_key=True, serialize=False),
        ),
    ]
